const API_BASE_URL = 'http://localhost:5000';
const NANOSECONDS_PY = 1;
const MICROSECONDS_PY = 1000 * NANOSECONDS_PY;
const MILLIESECONDS_PY = 1000 * MICROSECONDS_PY;

const MILLIESECONDS_JS = 1;
const SECONDS_JS = MILLIESECONDS_JS * 1000;

export { API_BASE_URL, MILLIESECONDS_PY, SECONDS_JS };
// export { API_BASE_URL: API_BASE_URL };